#!/usr/bin/env bash
# find out what’s keeping Ubuntu container’s Nginx installation from listening on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
